-- ==============================================================================
-- Project: E-Commerce RFM (Recency, Frequency, Monetary) Analysis
-- Description: SQL script to extract customer purchasing behaviors, calculate 
--              lifetime order values, and segment VIP customers.
-- ==============================================================================

SELECT 
    customer_id,
    
    -- Recency: Days since the customer's last purchase
    DATEDIFF(CURRENT_DATE, MAX(order_date)) AS recency_days,
    
    -- Frequency: Total number of orders placed by the customer
    COUNT(DISTINCT order_id) AS frequency_total_orders,
    
    -- Monetary: Total lifetime value (revenue) generated by the customer
    SUM(total_order_value) AS monetary_lifetime_value
    
FROM 
    ecommerce_sales
WHERE 
    order_status = 'Completed'
    AND order_date >= DATE_SUB(CURRENT_DATE, INTERVAL 1 YEAR) -- Focuses on the last 12 months
GROUP BY 
    customer_id
ORDER BY 
    monetary_lifetime_value DESC, frequency_total_orders DESC;
